name:          Front-end code style guide
description:   Standards for developing flexible, durable, and sustainable HTML, CSS and JavaScript

markdown:      rdiscount
permalink:     pretty
highlighter:   pygments
